### ISSUE TITLE
O jogo trava ao comprar muitas cartas

### ISSUE THREAD

**Issue by SamuelPimentel** [NathaliaQuetsia/last-card#6]
Quando você compra muitas cartas de uma vez o jogo trava

**Comment by NatSilva385** [comment]
esse erro ocorre devido a velocidade de compra de cartas?

**Comment by SamuelPimentel** [comment]
Acho que não, o problema deve estar relacionado com as cartas acabarem

**Comment by NatSilva385** [comment]
Checar se a PR #7 corrigiu o seu problema

**Comment by SamuelPimentel** [comment]
Resolveu sim
